version: '3.3'

services:

  database:
    image: mariadb
    container_name: database
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - TZ=Europe/Kiev
      - MARIADB_USER=irudakov
      - MARIADB_PASSWORD=211
      - MARIADB_ROOT_PASSWORD=gtfdfdf
      - MARIADB_DATABASE=mydb

volumes:
  db_data: